// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_perfect_master = "CgkIlsbB96oXEAIQBQ"; // <GPGSID>
        public const string achievement_classy_mind = "CgkIlsbB96oXEAIQDQ"; // <GPGSID>
        public const string achievement_welcome = "CgkIlsbB96oXEAIQAg"; // <GPGSID>
        public const string achievement_fighter = "CgkIlsbB96oXEAIQBg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIlsbB96oXEAIQDg"; // <GPGSID>
        public const string achievement_beginner = "CgkIlsbB96oXEAIQAQ"; // <GPGSID>
        public const string achievement_expert = "CgkIlsbB96oXEAIQAw"; // <GPGSID>
        public const string achievement_warrior = "CgkIlsbB96oXEAIQBw"; // <GPGSID>
        public const string achievement_lord = "CgkIlsbB96oXEAIQCA"; // <GPGSID>
        public const string achievement_breathtaking_mind = "CgkIlsbB96oXEAIQCw"; // <GPGSID>
        public const string achievement_secret_master = "CgkIlsbB96oXEAIQBA"; // <GPGSID>
        public const string achievement_super_mind = "CgkIlsbB96oXEAIQCg"; // <GPGSID>
        public const string achievement_topping_mind = "CgkIlsbB96oXEAIQDA"; // <GPGSID>
        public const string achievement_great_mind = "CgkIlsbB96oXEAIQCQ"; // <GPGSID>

}

